#!/bin/bash
set -e

# run the server
echo "==> Starting server..."
exec uvicorn --app-dir "${APP:-/app/src}" --host "${BIND:-0.0.0.0}" --port "${PORT:-8000}" \
  --proxy-headers --forwarded-allow-ips "${FORWARDED_ALLOW_IPS:-*}" \
  main:app
